### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by pavelloz** [annotorious/annotorious#10]
Hey, just wanted to say thank you for your constant work over the years. I remember using it long time ago (still old repo) for an internal experimental project and i just stumbled upon this repo - im amazed by your work. I hope more projects will be maintained so good (and long) :)

(And of course i stumbled upon it because im looking for annotations again, but react bundled in is a little bit too much for my taste :) )

**Comment by rsimon** [comment]
Thanks, I really appreciate that! :-) 

Yes, the last build (off the master branch) is around 380kB which is starting to become a bit big... (the old Annotorious was <100kB). I'll see whether I can get that down eventually. But, yes, React always felt to me optimized towards the "developer experience", so to speak, rather than performance or size.

Also, if you were using via npm, the current published package exposes the source, not the transpiled lib. Which means you have to add React & everything else to your own project dependencies. A mis-configuration on my part [that will also go away with the next release](https://github.com/recogito/recogito-js/issues/1) (later this week), in case this helps.

Anyways, hope it remains useful. Thanks again!

**Comment by rsimon** [comment]
P.S.: FWIW all the actual drawing is still React-free. It's just the annotation popup that's React - and that's imported from [another package](https://github.com/recogito/recogito-client-core). It would be totally feasible to have an old-school "Annotorious Light" with a simpler popup & (mostly) dependency free. Something for the future perhaps. (See also issue #5.)

**Comment by pavelloz** [comment]
Ive seen some success stories on migrating React -> Preact which is a lot smaller and advertised similar API, maybe that an option :) (Idea for crazy people like me: Svelte ;) )

> Also, if you were using via npm, the current published package exposes the source, not the transpiled lib. Which means you have to add React & everything else to your own project dependencies.

This actually might be a good idea for user to choose, because there is a lot of react apps and having two of them in one app seems wasteful :)

> P.S.: FWIW all the actual drawing is still React-free. It's just the annotation popup that's React - and that's imported from another package. It would be totally feasible to have an old-school "Annotorious Light" with a simpler popup & (mostly) dependency free. Something for the future perhaps. (See also issue #5.)

That would be very cool. Actually that would fit my use case very nicely, because what i do is to annotate images as an "admin" in a dashboard, and then view them as a normal user (read only).

**Comment by rsimon** [comment]
Good point - yes, I'll definitely check out Preact, thx.

**Comment by rsimon** [comment]
FYI: I switched to Preact and added the UglifyJS plugin to the build - and that brings down the final bundle to 105kB. (Actually better than the original, since this also includes the CSS styles + has editable shape functionality.)

**Comment by pavelloz** [comment]
Haha, that was quick :)

Pretty nice return on investment (ive seen the commit :) )
