### ISSUE TITLE
Wrong editor positions in Firefox when using shape labels

### ISSUE THREAD

**Issue by KennySmash** [annotorious/annotorious#164]
I was doing some browser testing with my app and found this weird positioning bug in Firefox:
Confirmed to work fine in Edge, Chromium and Safari in sane versions 

it seems to only affect annotations that spawn the editor below the note, as all notes that spawn above the target get drawn correctly

![Screenshot 2021-09-13 at 11 25 39](https://user-images.githubusercontent.com/7831621/133068769-eab76c70-3245-43d5-98ca-265ea6c3ac7d.png)

**Comment by KennySmash** [comment]
I can't seem to recreate it with the demo's on the project page, going to try do it via JSFiddle

**Comment by rsimon** [comment]
Yikes... so the offset placement also happens for the "small note" and "page 3" annotation in your case? Is there something special about the image container? E.g. is there any page scroll involved? Or things like absolute positioning (or other CSS styles) on the image element directly?

**Comment by KennySmash** [comment]
Small note does the offset but page 3 works fine cause it puts the editor on top. 

When changing the page, I destroy the annotations, change the background page and then set the size of the element so that the document always fits on the page
![Screenshot 2021-09-13 at 11 38 25](https://user-images.githubusercontent.com/7831621/133069977-f4ea412f-2e55-4c4b-89a7-b570660953c4.png)

think it could be an issue where the canvas bounds don't get updated on page change?

here is the style stack for the img element: 
![Screenshot 2021-09-13 at 11 42 22](https://user-images.githubusercontent.com/7831621/133070226-647da5df-13d2-4816-abc1-34adb88eeb46.png)

**Comment by KennySmash** [comment]
here is an extreme case : 
![Screenshot 2021-09-13 at 11 47 19](https://user-images.githubusercontent.com/7831621/133070826-6256ea95-57fb-45e1-b6cc-0d1210399eba.png)

**Comment by rsimon** [comment]
Hm, I think if it were the Canvas bounds not getting updated, it should probably affect all browsers. FWIW, the default editor orientation (= editor below the note) works by grabbing the shape bounding client rect, and then setting the editor `top` and `left` style props.

```js
// wrapperEl is the DIV created by Annotorious, around the image element (=common parent to image + SVG layer)
const containerBounds = wrapperEl.getBoundingClientRect();

// selectedEl is the SVG group element of the annotation (= the one with the .a9s-annotation class)
const { left, top, right, height, bottom } = selectedEl.getBoundingClientRect();

editorEl.style.top = `${top + height - containerBounds.top}px`;
editorEl.style.left = `${left - containerBounds.left}px`;
```

I wonder if there's a case of FF vs. the rest interpreting coordinate space in a different way, under some circumstances?

**Comment by KennySmash** [comment]
It seems to weirdly double an axis on the editor but always works in the case of annotation creation, in my first screenshot, the editor is floated below by the exact amount that the annotation is from the top, but sometimes it changes from doubling the y axis to the x axis

so it seems it could be something in how relative coords is handled in FF

**Comment by KennySmash** [comment]
The Div that the img sits in has `position: relative;` but playing around with that doesn't seem to do much

**Comment by rsimon** [comment]
No, that just causes the editor's top/left props to be relative to the wrapper DIV. Hm, it's really weird because the default orientation seems fairly fool-proof.  `getBoundingClientRect` returns coordinates relative to the viewport, i.e. the code simply gets the bounds of the annotation (relative to the viewport) and then corrects that by the viewport offset of the parent, making top/left relative to the parent.

Either something has to be wrong with the top or height of the SVG shape bbox, or containerBounds.top. My guess is that the height might be the cause of the error. (I used to have problems with incorrect height values in some browsers previously.) Anyways: if you can post a JSFiddle, that would be ideal. That way I can try to play with things in the browser console & see if I find anything.

**Comment by KennySmash** [comment]
Here is a video of the bug in action

[![Image from Gyazo](https://i.gyazo.com/4231c830fee49f49d881a40b8a9e0ab6.gif)](https://gyazo.com/4231c830fee49f49d881a40b8a9e0ab6)

**Comment by rsimon** [comment]
Ah - wait. Now maybe I'm compeletely on the wrong path here. But what I *did* see is that Firefox has a weird bug (or, at least, alternative interpretation of the standard) when it comes to SVG element sizes. My hunch is it may actually be caused by the shape label element, which then stretches the annotation shape height prop.

That would also explain why you can't reproduce it with the demos on the Annotorious website (because they don't use the shape labels plugin). In principle, that should be easy to verify with a JSFiddle. (Checking what the actual bbox size is in FF.) And then it probably needs a change in the Annotorious code, to make sure the bbox used for position is that of the inner rectangle + the inner shape label DOM element, not the outer container which might get messed up by FF.

Anyways: I could be wrong with this though. But my best (and only :-) guess now.

**Comment by KennySmash** [comment]
Hit the nail on the head, I took out my label code on the formatter and lo, its working properly
so really accurate guess there 😁

**Comment by rsimon** [comment]
Yay! So at least we have the issue diagnosed. I'll put that on the list - should be easy to fix now that we know how to reproduce it.

**Comment by rsimon** [comment]
For posterity. Here's what Chrome thinks the size & position of the SVG shape label is (=correct):

![image](https://user-images.githubusercontent.com/470971/133879221-e3c484b7-199f-460a-b9b2-ca2a975663ac.png)

And here's what Firefox thinks:

![image](https://user-images.githubusercontent.com/470971/133879236-af17279c-6a6b-47e7-bbbc-ae30f183b42c.png)

The nested SVG has the correct x/y/width/height attributes set. But FF extends the size of the nested SVG to top left of the parent SVG, leading to the false offset. I don't quite know how to deal with that. 

Note to self: the nested SVG seems necessary, since it allows people to position elements inside it, using coordinates relative to the annotation, rather than the whole image. But perhaps another way to achieve that would be by using an SVG group (instead of a nested SVG) and applying a transform that updates accordingly.

**Comment by rsimon** [comment]
PS: alternative approach might be to tweak the way editor positioning works, and use `bottom` of the annotation rather than `top` + `height`. (Which is how it works now.) Probably more sane, anyway.

**Comment by rsimon** [comment]
Turns out size computation/interpretation is terminally broken in Firefox. I managed to find a fairly simple solution that works in FF, but not Chrome. So the fix now includes browser sniffing which applies the FF solution if FF is detected, and keeps standard formatting otherwise. Not ideal, but does the trick. 

Incidentially, I wanted to roll a new release this weekend, anyway, so this will be live ASAP.
