### ISSUE TITLE
BUG: Error trying to use annotorious package in Next/React app

### ISSUE THREAD

**Issue by jacklynch00** [annotorious/annotorious#180]
After reading though the documentation, it appears that you all are aware that there is not full support for this package in react apps. That being said, I thought I would still document a bug I've been experiencing. When trying to initialize the annotate instance (code snippet below) and the other code that goes into initialization according to the docs, I get thrown a reference error `window is not defined` which traces back to a distribution/minified file.

```
annotorious = new Annotorious({
    image: imageRef.current
});
```

**Comment by rsimon** [comment]
I'm not an expert in NextJS. But from the sound of it, I suspect you're attempting to do the wrong thing: Annotorious works entirely in the browser. "window is not defined" sounds like your Annotorious init code is executed in node.js, on the server/during build. There's no way this can work, because Annotorious needs to run client-side. 

Something like this might provide some insight:
https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97

Especially solution no. 3 (dynamic loading) sounds like what you're looking for. This makes sure Annotorious is left out during SSR, and only executed in the browser.
