### ISSUE TITLE
Is there  way to rotate annotation box?

### ISSUE THREAD

**Issue by NarGhazaryan** [annotorious/annotorious#183]

**Comment by rsimon** [comment]
Hi, no the built-in rectangle tool doesn't support rotation. (On the one hand, simply because this isn't implemented as a feature yet. On the other hand, because the rectangle is stored as a [W3C Web Annotation Fragment Selector](https://recogito.github.io/annotorious/getting-started/web-annotation/), which strictly only supports rectangles parallel to the image.)

But I agree it would be an interesting feature for the future. Feel free to create a feature request ticket on the Selector Pack issue tracker:

https://github.com/recogito/annotorious-selector-pack/issues

(The selector pack is a plugin for additional selection tools like the one you describe.)
