### ISSUE TITLE
Rotating div wrapping anno image by 90deg causes corner handles to double in size

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#218]
I am seeing an issue where if I rotate the div wrapping the anno image by 90deg using transform: rotate(90deg), and select a label, the corner handles double in size.
Is there a workaround for this ? I want the corner handles to remain at a particular size like 6.

I'm using Annotorious in headless mode.

**Comment by rsimon** [comment]
Hi,

unfortunately, that's indeed a bit of a special case. I can reproduce it, and I can see what's going on. But I'm afraid it's not going to be entirely fixable. A bit of context & explanation:

In order to support responsive websites, Annotorious up- or downscales the handles when images are scaled. E.g. if a responsive website scales the image (and the annotation layer) down, Annotorious up-scales the handle in order to make them appear at constant size.

In order to compute that scaling factor, Annotorious uses the true width and height of the image, and the scaled current bounds of the SVG annotation layer. Now, if you flip the image by 90 degrees, that computation breaks. E.g. if you have an image 200px wide and 100px high, and rotate 90 degrees, the handles will get upscaled by a factor of 2. Because Annotorious sees the image as down-scaled to 50%.

I can't think of a good solution how to make this auto-scaling support arbitrary rotation, TBH. (Also because I don't know off the top of my head how to reliably determine the rotation of the annotation layer, if any of the parent elements has a CSS rotation applied.) But I can add the following small tweak to the next release: I can add a `transform-origin` property to each handle which would allow you to scale the handles yourself, outside of Annotorious. This way, you could apply the following CSS rule: 
```css
.a9s-handle circle {
  transform:scale({some factor});
}
```

And this would then down-scale the handles again. (The `transform-origin` fix would make sure that handles are scaled around their center, and not get shifted because of the scale.) 

Note that `{some factor}` would have to be determined by the aspect ratio of your image (factor = height / width); and you would have to apply the rule __only__ if the image is rotated!

(P.S.: I'm not covering the case of rotations between 0 and 90 deg... then you'd probably need to mix in a bit of trigonometry, too.)

Anyways, the code where the scaling is computed inside Annotorious is here:
https://github.com/recogito/annotorious/blob/main/src/tools/Tool.js#L47-L58

If you manage to figure out a cleverer solution, do let me know & we can incorporate.
