### ISSUE TITLE
Is it possible to allow only one comment in the comment widget ?

### ISSUE THREAD

**Issue by AlexMili** [annotorious/annotorious#222]
I know this is a very specific use case, but I need to allow only one comment and disable further ones. I looked inside [Comment plugin](https://github.com/recogito/recogito-client-core/tree/main/src/editor/widgets/comment) without success. Since I use VueJs and not ReactJs, developing my own widget sounds complicated. If it's not possible I will found another way, I wanted to be sure it was (not) possible before beginning tweaking around.

**Comment by rsimon** [comment]
That's right - it's not currently possible I'm afraid. Once chance, perhaps, would be to brute-force hide the reply field using CSS. The editable edit fields (including the reply field) all have a `.r6o-widget.comment.editable` class. And you could just apply `display:none`.

It's tricky though, because you'd need to check if there is more than one `r6o-widget.comment`. Otherwise, the rule would also hide the first comment field.

**Comment by AlexMili** [comment]
Ok, thank you for your answer :)
