### ISSUE TITLE
Un-minified CSS file

### ISSUE THREAD

**Issue by EmKarr** [annotorious/annotorious#240]
Is there a un-minified version of "annotorious.min.css" for easier customization?

Best,
Michael

**Comment by rsimon** [comment]
No, there's no unminified version (because it's generated from multiple SCSS files, distributed between Annotorious and the [recogito-client-core package](https://github.com/recogito/recogito-client-core/tree/main/themes/default)).

However, the minification doesn't garble anything (like JS minification does). It really only collapsed formatting. So you could simply take the CSS file and auto-format it in a code editor, like VSCode, if you want better readability. 

In general though, I'd recommend against changing the file directly. You can simply write your own styles to override the rules you want to override.
