### ISSUE TITLE
Set different stroke colors and label shape

### ISSUE THREAD

**Issue by Seokkitdo** [annotorious/annotorious#249]
Hello! 

I am new to using Annotorious, so I have some questions about it.

Q1. Is that possible to set different stroke color using `formatter` option not using css file. 
I saw #81 but I will use several imgs and get imgs infos(position, labelname) from server

Thanks for any help and appreciate your work

**Comment by rsimon** [comment]
Hi,

you can also set CSS styles directly (e.g. "stroke: red" etc.), not just CSS classes. See the `style` example at:
https://recogito.github.io/annotorious/api-docs/annotorious/#object-example

BTW: formatters are a bit underdocumented on annotorious.com. There's also a more in-depth tutorial here:
<https://observablehq.com/@rsimon/writing-annotorious-formatters-pt-1>
<https://observablehq.com/@rsimon/writing-annotorious-formatters-pt-2>

**Comment by rsimon** [comment]
The articles explain the basics. Formatters work __on each individual annotation__. Based on the annotation data, you can attach different CSS classes. If you do that, you'd have to define those classes globally in your CSS stylesheet, yes.

But instead of returning a string from the Formatter (which would get added as a CSS class) you can also return an object (see API docs). E.g. something like this:

```js
{
  style: 'stroke:red; fill:rgba(255,255,255,0.2)'
}
```

This will then become an inline style for the annotation.

**Comment by Seokkitdo** [comment]
I solved it! Really appreciate about answer!! I misunderstand the working of formatter function.  
After typing console.log I realize what's wrong. 

``` let contributors = []
    let colors = []
    annotation.bodies.forEach(function (body) {
      colors.push(body.color)
      contributors.push(body.value)
    })

    // console.log(contributors.join(', '))
    // console.log(colors.join(', '))

    return {
      'data-users': contributors.join(', '),
      style: `stroke-width:2; stroke: ${colors.join(', ')}`
    }```
