### ISSUE TITLE
Touch scrolling

### ISSUE THREAD

**Issue by gbrits** [annotorious/annotorious#263]
Hi there, I'm using Annotorious for my mobile app and I have found that I cannot scroll on a "zoomed in" image that has Annotorious enabled on it as I presume the touch gets taken up by Annotorious. If I `setVisible(false)` I can scroll up & down and left and right as standard. Any advice?

**Comment by rsimon** [comment]
Hi,

yes, `setVisible` will hide the SVG annotation layer (using CSS `display:none`). Just to confirm: are you using Annotorious standard, or the OpenSeadragon version?

Either way, touch events on the image are, by design, going to trigger drawing (in Annotorious standard) or image navigation (Annotorious OSD). If the image is taking up the whole screen and you still want to be able to scroll the page, there's no way around building your own toggle button. This way, you could keep `setVisible` to false by default, allowing normal page scroll. And only when the user clicks a "Start Drawing" button (or whatever), `setVisible` would get switched on, scrolling would be blocked, and drawing would work.
