### ISSUE TITLE
Preserve ordering of annotations in the SVG?

### ISSUE THREAD

**Issue by kennysong** [annotorious/annotorious#268]
Hi! Annotorious is a fantastic library, and our team has found it very useful for visualizing ML model predictions.

We've noticed that the order of annotations passed to `anno.setAnnotations()` is not preserved in the generated SVG. Is this intentional? If so, is there a way to use the same ordering as the original array of annotations?

Our use case is that we also display labels above each annotation with [the shape labels plugin](https://github.com/recogito/recogito-client-plugins/tree/main/plugins/annotorious-shape-labels), and since the labels sometimes overlap, we'd like them to stack/draw in a specific order for readability.

**Comment by rsimon** [comment]
Hi!

Thanks! Yes, the shuffling is intentional - and I'm afraid there's no way to change it in Annotorious, except by forking it. 

Annotorious sorts the shapes by size, and then stacks them so that the largest shape is at the bottom (added to the SVG first), and the smallest shape is at the top (added last). This way, no large shape will overlap a smaller shape, and all the shapes remain clickable. 

If forking _is_ an option for you, however: the change would be fairly minimal, I believe. Shouldn't take much more than commenting out [this section](https://github.com/recogito/annotorious/blob/main/src/AnnotationLayer.js#L341-L350) in the annotation layer (or, alternatively, remove every call to `redraw()`).

The other alternative would be to switch to the [OpenSeadragon version of Annotorious](https://recogito.github.io/annotorious/getting-started/osd-plugin/). This doesn't do any reshuffling, because it handles hit/hover detection in a different way (by querying a spatial index instead of relying on mouse events.)

Hope this helps!

**Comment by kennysong** [comment]
Thanks for the quick reply! Your explanation of how the ordering algorithm works was quite helpful.

We found a workaround by re-ordering a selected annotation to the "top" of the SVG so the label is always visible (and reseting it to its original position when deselecting). This preserves clickability and readability in our use case.

**Comment by kennysong** [comment]
Hi @rsimon, quick follow-up question: 

We switched to the OpenSeadragon version of Annotorious to be able to use zooming. You mentioned that

> it handles hit/hover detection in a different way (by querying a spatial index instead of relying on mouse events.)

I just wanted to confirm that the order of `.a9s-annotation` elements in the SVG no longer affects hovering and clicking? This seems to be the behavior we observed during testing.

**Comment by rsimon** [comment]
Hi, yes that's right. The order of the SVG elements in the DOM is irrelevant to hit detection in the OSD version.

**Comment by kennysong** [comment]
Thanks for confirming! This is really useful, we no longer need to reset annotations "to its original position when deselecting" anymore.
