### ISSUE TITLE
Conditional Widget

### ISSUE THREAD

**Issue by abramzog** [annotorious/annotorious#289]
Is there a way to configure a conditional widget?
Example Scenario:
A widget with a radio button (`on & off`) that by setting it `on`/`off` it will render/remove another widget?

**Comment by rsimon** [comment]
Sorry for the late reply. Yes, you can change the widgets during runtime. You'd need to build your own UI for the toggle switches etc. But otherwise, `.widgets` field can be altered any time, and the editor will reflect the new widget config.

https://annotorious.github.io/api-docs/annotorious/#widgets
