### ISSUE TITLE
Unable to annotate in IE11 Windows 10

### ISSUE THREAD

**Issue by dennisgaebel** [annotorious/annotorious#29]
console error reported

![Screenshot 2020-06-10 15 31 53](https://user-images.githubusercontent.com/13485205/84310426-a0ee3600-ab2f-11ea-9baa-202c9536e71c.png)

**Comment by dennisgaebel** [comment]
pretty sure this just needs the `classList` polyfill

**Comment by rsimon** [comment]
Weird. Docs seem to say that `classList` should be available from IE10 onwards. But I agree, that looks like the only occurrence of an `.add` in the code.

**Comment by hopkinsaaron** [comment]
Hi Simon, Love your Annotation tool. We (NHS WALES, UK) have integrated it in one of our .Net projects - so providing medical professionals the ability to comment/tag areas of the body (or any image for that matter).

We are currently on v.2.0.4. - but are waiting on this IE11 bugfix before we can go live with it.
Any movement on this one?

Our deadline is probably the week commencing 14th Sept 2020 - so a fix and release before then would be fantastic, so that we can integrate and test prior to go live.
Sorry for the hassle factor - but we love your tool so much, we just have to use it!

Kind Regards
Aaron Hopkins
Senior Analyst Programmer - NHS Wales, UK

**Comment by rsimon** [comment]
Well, if it supports the NHS ;-) I looked into this yesterday and it seems like it's primarily about adding (a million...) polyfills. I patched several yesterday. But there are still two remaining problems, with the editor popup position; and IE11 not supporting Promises which are used in the `loadAnnotations` API method. I'll try to look into these soon-ish. Can't give any firm guarantees though.

**Comment by rsimon** [comment]
Quick update on this: I think I managed to resolve most of the issues and just published a new version of [recogito-client-core](https://github.com/recogito/recogito-client-core), the core library Annotorious depends on. Should be able to publish a new Annotorious release with IE11 support soon.

**Comment by hopkinsaaron** [comment]
This is fantastic news for us Simon.. thank you.
I'm looking forward to incorporating the next release into my source. :)

Thank you for acting so quickly, It puts my mind at ease and makes it so
much easier to invest in the project, knowing the developer cares is a
massive plus.

If you need a testimonial - please ask.
If you would like to name us as a consumer - feel free.

Kind Regards
Aaron.
NHS Wales, UK

**Comment by rsimon** [comment]
I just published a new release ([2.0.7](https://www.npmjs.com/package/@recogito/annotorious)). This should address most IE11 problems. There are still a few display issues with the tagging widget which, I think, are mostly CSS stuff that I still need to figure out.

An updated release for [the OpenSeadragon plugin](https://github.com/recogito/annotorious-openseadragon) is about to follow soon.

Yes, a testimonial would be awesome! Can you drop me a quick email at aboutgeo(at)gmail.com?

**Comment by rsimon** [comment]
I added a few additional CSS fixes (concerning the tag widget). These will become available with the next release. @Everyone ping me in case you run into any further IE11 issues :-)
