### ISSUE TITLE
Why the annotation lifecycle properties of the `Annotation` are present on the `AnnotationTarget`?

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [annotorious/annotorious#325]
Could you clarify why are the `created`, `creator`, `updatedBy`, and `updated` specified on the `AnnotationTarget` and not the `Annotation` itself?...
According to the spec, only the parent annotation can have those, but not the target 🤔 
https://www.w3.org/TR/annotation-model/#lifecycle-information

https://github.com/annotorious/annotorious/blob/4a36371ea227973d72aaf93ca79980a314b30597/packages/annotorious-core/src/model/Annotation.ts#L19-L33

**Comment by rsimon** [comment]
I don't think the spec explicitly prohibits them. Either way: that's the internal model after all. The reasoning behind it is that targets and bodies can be created pretty much independently (think of multiple shapes, and comments and replies). The annotation itself is really just a container. 

In that sense, I've always thought of the `created` / `creator` info at the annotation level as a piece of derived information - whoever was the first creator of the first part of the annotation. In addition, realtime systems will need to push around targets and bodies independently from the rest of the annotations (hence the `annotation` field to connect them). And IMO it's a lot better to keep that info together rather than spread out. (For as similar reason, Annotorious also doesn't use `motivation` at the annotation level. In general, annotations can be lists of bodies all with different `purposes` (tagging, commenting, replying etc.)

**Comment by oleksandr-danylchenko** [comment]
> The reasoning behind it is that targets and bodies can be created pretty much independently

Aha, I'm on the same page now. But it might mean that the existing W3C adapter should be reworked a bit to prevent losing those properties. Because now on parsing those lifecycle props are not being assigned to the `target` and on serialization, they are not lifted from the `target` to the `Annotation` level

**Comment by rsimon** [comment]
Yes, I agree. That bit should probably be revised, for better spec compatibility.

**Comment by oleksandr-danylchenko** [comment]
PR is on the way 🚀

**Comment by rsimon** [comment]
I think this one's now good to close, with your latest PRs merged, right?

**Comment by oleksandr-danylchenko** [comment]
Yeah, now we have the lifecycle props preserved. Thanks 🙌🏻

**Comment by rsimon** [comment]
Thanks for your contribution! BTW: I haven't forgotten on the PRs on Text Annotator. But, frankly, Text Annotator is a bit lower on my priority list, as far as my current running projects are concerned. So it may take a while until I get to that. But thanks in advance already ;-)
