### ISSUE TITLE
Missing ID for selected annotation in headless mode 

### ISSUE THREAD

**Issue by scandella** [annotorious/annotorious#370]
Using Annotarious V2 in headless mode, when saving annotations, no ID is generated into the annotation object for the annotation currently selected.
Then when loading the previously saved annotation, an error is raised for this particular annotation. 

Steps to reproduce:
1. init Annotarious in headless mode `anno.disableEditor = true;`
2. create some annotations, keep one selected
3. save the annotations
4. the annotation selected has a "selected" type, but no ID
5. load this Annotarious object
6. the annotation without the ID raised an error and cannot be manipulated

Adding an ID to the selected annotation fixes the problem.

Thank you for your very nice project.

**Comment by rsimon** [comment]
That's the desired behavior. As long as the annotation isn't "created" yet, it doesn't get an ID. You need to click outside of the annotation at least once in order to confirm it's creation. (At this point, it will get an ID.) Until you haven't done this, the object will have a `type` of `Selection` (not `Annotation`), and no ID.
