### ISSUE TITLE
Should the `openseadragon` be made a required dependency?

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [annotorious/annotorious#435]
## Issue
Currently, the `openseadragon` **is required** to be present to bundle the `@annotorious/openseadragon` and the dependent `@annotorious/react`: 
![image](https://github.com/user-attachments/assets/f4920b3c-aa40-4d71-858c-fe0d2a4c066a)

However, the `openseadragon` is described as _an optional peer_: https://github.com/annotorious/annotorious/blob/e6a5ad1bbebc3fd2eeda343ed265490e4047dd48/packages/annotorious-react/package.json#L35-L44
Which requires the consumer apps to add it to their dependencies list explicitly.

Therefore, if the `openseadragon` is essential to bundling the `@annotorious/react`, should we make it just a dependency, not a peer dependency?

**Comment by rsimon** [comment]
I think this would also mean that the version of OSD would be dictated by Annotorious, though, which I think wouldn't be appropriate.

**Comment by oleksandr-danylchenko** [comment]
Hmm 🤔, that's a fair concern...
I think that then we might need to play with making the `OSD` an "external" dependency on the Vite level. So it won't block the bundling, and will just leave the `import {} from 'openseadragon'` statements as-is. But the consuming app, having the dependency installed, will run that code properly. 
I think I already did something similar in https://github.com/annotorious/annotorious/pull/388 🤔

**Comment by rsimon** [comment]
Yes, I think declaring it external might work. Although not sure it would change anything in the library build? Since it's already a peer dep only?

**Comment by rsimon** [comment]
I've been following up on this. Good news first:

- In the vite config, openseadragon is already external, because of [this line](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-react/vite.config.js#L28).
- I made a minimal example project that uses React and Annotorious, in image (but not OpenSeadragon) mode. This worked well, without OpenSeadragon installed.
- Because of the peerDependency, OpenSeadragon (latest version) got installed into the `node_modules` folder. But when building the app, OSD wasn't bundled into it. (Verified with the [vite-bundle-visualizer](https://www.npmjs.com/package/vite-bundle-visualizer))

__However:__

In my minimal example project, I used Vite as the bundler. My suspicion is that webpack may not honour the optional peerDependency setting in the same way. For example, my minimal example did not work with Codesandbox's default React  template (which uses create-react-app and webpack underneath the hood I believe).

**Comment by oleksandr-danylchenko** [comment]
Right... In our main project, we use the Yarn 1 + Webpack. And, unfortunately, the `OpenSeadragon` isn't getting installed automatically or picked during bundling.
Thank you for testing the different options 🙌🏻

**Comment by rsimon** [comment]
FWIW: I now also confirmed with Webpack 5 that this seems to work. It's installing `openseadragon` into the `node_modules` folder, but isn't including it into the app bundle if Annotorious OpenSeadragon isn't used. I'm sure there will be a million edge cases where this can fail (and we'll have to find out). But for now I think we should keep the build setup as-is.

As I'm approaching the official 3.0 release, I'm also starting to build a collection of basic "how-to" examples here:
https://github.com/annotorious/annotorious-examples

The first two I built just now are for Annotorious/React + Vite and Webpack. (Without OpenSeadragon, in both cases.)

**Comment by rsimon** [comment]
Just wondering: is this good to close, or still a problem?

**Comment by oleksandr-danylchenko** [comment]
I think that it can be closed, as the issue turned out to be in the older Yarn 1 that doesn't install the `peerDependencies` automatically.

**Comment by rsimon** [comment]
Cool, thanks for the update!
