### ISSUE TITLE
Editor Widgets after build  doesn't show

### ISSUE THREAD

**Issue by long912** [annotorious/annotorious#444]
In Vue, the custom component for Editor Widgets displays correctly in the local environment but doesn't show up after being bundled for production.
![image](https://github.com/user-attachments/assets/e81fe074-d800-4fe8-bb96-a3e12bad9517)

![image](https://github.com/user-attachments/assets/8ed22397-d788-4032-9367-cf1dca629713)

**Comment by rsimon** [comment]
Sorry for this. I'm afraid this may be an unsolvable problem (and one of the reasons that the new version of Annotorious, v3, is a complete re-write). It's related to the way Annotorious v2 determines whether a widget is a vanilla JS widget, or a React widget.

You might have a chance by overriding the autodetect process, using the (undocumented) `force` option:

```js
var anno = Annotorious.init(viewer, {
  widgets: [ 
    { widget: MyWidget, force: 'plainjs' }, // or 'react'
    'COMMENT',
    'TAG'
  ]
});
```

In the long run, I'd recommend switching over to version 3 of Annotorious, since I won't be able to support v2.7 any more.

P.S.: for some additional info around the problem see these related issues:
https://github.com/annotorious/annotorious/issues/202
https://github.com/annotorious/annotorious/issues/172
