### ISSUE TITLE
Polygon with duplicate points

### ISSUE THREAD

**Issue by technbuzz** [annotorious/annotorious#447]
I have drawn polygon with four point but I get **six points** in geometry. Is it normal?

**Comment by technbuzz** [comment]
![annotorious polygon bug](https://github.com/user-attachments/assets/5b34297b-419b-4650-8941-22b0078c5134)

This happens if your polygon visually have six points the geometry shows 8 points.

**Comment by technbuzz** [comment]
I thought i had to double click to complete the polygon path. Double click would add two more points. Instead I had to click on first to finish the annotation. I would close the issue with the question **What are other ways to complete the annotation**?

**Comment by rsimon** [comment]
Well, the _plan_ is that clicking the first point, as well as a double click should close the polygon. But it's still incomplete. 
- I still want to add visual feedback when hovering over the first point, as a hint that this will close.
- The duplicate points for double click are a known issue. (Single click always creates a new point. Because you'll only know after the fact whether it's going to be a click or a double click, I still need to add a bit of extra logic to clean up the duplicates afterwards.)
