### ISSUE TITLE
xywh lost when moving an annotation

### ISSUE THREAD

**Issue by hopkinsaaron** [annotorious/annotorious#60]
Hi Simon

For version 2.0.7
When moving an annotation - the xywh string is lost in the updateAnnotation function somewhere

example from my code :
 anno.on('updateAnnotation', function(a, previous) {
   console.log('updated', previous, 'with', a); 
   alert(a.id); // id populated
   alert(a.xywh); //not populated - expecting: new xywh position
 UpdateTableEntry(a); .//my method expecting a fully populated/updated annotation object
}

perhaps I am missing an event here? onMove perhaps

For info, I am unable to use versions > 2.0.7 currently as something introduced after 2.0.7 has made the overlay appear beneath the annotated image. I think it's since an attempt to make the annotation edit, modal - so if possible - if you could fix this 'xywh lost when moving an annotation' issue in ver 2.0.7 (and re-release it) that would be awesome?

All the best

Aaron.

**Comment by rsimon** [comment]
Thanks for reporting. Will look into it! 

I guess the thing you're missing with the current version(s) is that they no longer embed the CSS styles with the JavaScript. You now need to import the stylesheet in addition to the JavaScript file. See here:
https://recogito.github.io/annotorious/getting-started/

I'm afraid I won't be able to back-port fixes to previous versions though... would start being too much for me to manage in the long run. I'm happy to accept pull requests though!

**Comment by hopkinsaaron** [comment]
Hi Simon,

Thanks for getting back to me.
After a fair amount of head scratching, I managed to fix this issue..

It only occurs when the 'previous' object is not passed through to my function.
i get a fully populated annotation when i pass 'previous', but without passing 'previous' i get a fragment...
[This is the whole object in full]
 {
                "source":"http://localhost/ImageAnnotationTool/images/myimage.png",
                "selector": {
                            "type":"FragmentSelector",
                            "conformsTo":
                            "http://www.w3.org/TR/media-frags/",
                            "value":"xywh=pixel:226,27.28125,65,55.71875"
                            }
                }
very odd, but also very true.
it's strange because i would have thought that this behavior if true would be negated by the use of 'previous' in the console.log ... but as it stands, without passing 'previous' through my function this fragment is created and passed as an annotation, breaking any expectant code elsewhere.
Perhaps a note in the docs for this might be useful to the next guy. 

Please close this bug at your leisure.

Aaron

Ps. also noticed when this bug is occurring that the update method fires as soon as the annotation is moved.
but when its working, the update is fired when the user finishes moving the annotation, and then clicks OK, as expected.

**Comment by rsimon** [comment]
Hi,

hm, I'm not sure I understand what's going on in your case. The way it's supposed to work (and which I just confirmed working in the current release) is this:

- When you move the annotation, nothing happens initially
- When you hit 'OK' on the moved annotation, the `updateAnnotation` event fires. The handler function will get the updated annotation as the first argument, the previous annotation as the second
- You won't get fragments, or just selectors, etc. Both arguments are __full__ annotations

Example - let's say you have the following handler attached to your anno instance: 

```js
anno.on('updateAnnotation', function(annotation, previous) {
  console.log('updated', previous, 'with', annotation);
});
```

...then `previous` could look like this...

```json
{
  "@context":"http://www.w3.org/ns/anno.jsonld",
  "id":"#a88b22d0-6106-4872-9435-c78b5e89fede",
  "type":"Annotation",
  "body":[
    {"type":"TextualBody","value":"It's Hallstatt in Upper Austria"}
  ],
  "target":{
    "selector":[{
      "type":"FragmentSelector",
      "conformsTo":"http://www.w3.org/TR/media-frags/",
      "value":"xywh=pixel:273,171,123,94"
    }]
  }
}
```
and `annotation` would look like this:

```json
{
  "@context":"http://www.w3.org/ns/anno.jsonld",
  "id":"#a88b22d0-6106-4872-9435-c78b5e89fede",
  "type":"Annotation",
  "body":[
    {"type":"TextualBody","value":"It's Hallstatt in Upper Austria"}
  ],
  "target":{
    "selector":[{
      "type":"FragmentSelector",
      "conformsTo":"http://www.w3.org/TR/media-frags/",
      "value":"xywh=pixel:382,23,123,94"
    }]
  }
}
```

Note that nothing has changed about the annotation, except the value of the fragment selector.

P.S.: concerning your example above, `annotation.xywh` is not a field that annotation has, so that would always return `undefined`. You need to dig down into the selector (`annotation.selector[0].value`) to get the coordinates.
