### ISSUE TITLE
Disable Editing / Deleting for a specific reply (Hacky solution inside)

### ISSUE THREAD

**Issue by nikita-kazakov** [annotorious/annotorious#61]
First, thank you for making this tool. It's well designed and has a lot of potential.

# Issue
I'll have multiple users replying to an annotation. When a specific user clicks on the annotation, it would be nice to have them edit only their replies. The other replies should be read-only and without the edit/delete dropdown. Is there a way to do that?

# Hacky Solution

I found a hacky solution that will suffice on my end for now. I wanted to mention it in case someone else is looking to do this.

Make sure to use `setAuthInfo` so that each conversation is associated with a `displayName`.

Use the `selectAnnotation` event handler. When an annotation is selected, I used JQuery to find the label boxes that are NOT the current user that is logged in. I then traverse up using `parent()` to find the `.icon` and hide that.

Here's the javascript code:
```
var removeEditDropdown;

removeEditDropdown = function() {
  return $(".lastmodified-by:not(:contains(" + asset.userName + "))").parent().parent().find('.icon').hide();
};

anno.on('selectAnnotation', function(annotation) {
  $('.icon.arrow-down').show();
  return setTimeout(removeEditDropdown, 40);
});
```

`setTimeout` had to be used or otherwise there's not enough of a delay to remove the drop down elements.

Is it pretty? No. But it will suffice for now.

Here's the result:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/40440087/94623355-35aca900-0271-11eb-9224-bf6c66fc95d7.png">

**Comment by rsimon** [comment]
Hi, thanks for the positive feedback. I appreciate that!

For your specific case (disabling the editing of other users' comments): in fact there's a proper solution available since one of the recent releases ([v2.1.0](https://github.com/recogito/annotorious/releases/tag/v2.1.0)). But that's still so new I didn't get around to properly documenting it yet... 

The comment widget now supports an additional `editable` config option. In your case, the initialization should look like this:

```js
var anno = Annotorious.init({
  image: '...',
  widgets: [
    { widget: 'COMMENT', editable: 'MINE_ONLY' }
  ]
});
```

This init config will give you an editor popup like in your image (comments & replies, but no tagging), and the comment widget will have the __MINE_ONLY__ editing rule set:

> The comment widget now has an additional editable config option so you can switch (separately from the global setting) between editable (editable: true), not editable (editable: false) and editable, but don't allow editing other users' contributions
(editable: 'MINE_ONLY).

Hope this helps.

**Comment by nikita-kazakov** [comment]
Fantastic! Thank you so much for the quick reply and for describing the solution to this!

**Comment by dosstx** [comment]
Hello, this is related to this feature, but how to also prevent a user from moving the annotation if he did not originally create it? It seems to me this should be included in this disabling functionality?
