### ISSUE TITLE
readOnly mode displays html code for multi-line annotations

### ISSUE THREAD

**Issue by ricardoroth** [annotorious/annotorious#65]
To reproduce:

- Create an annotation with multiple lines.
- Switch to readOnly: true
- open the annotation.

Problem: <div> html tags where used to create the lines, but they show up escaped on readOnly mode.

![image](https://user-images.githubusercontent.com/9203988/97642131-0e7cff00-1a0a-11eb-8a6d-1e50a7583d36.png)

**Comment by rsimon** [comment]
Thanks for spotting. I don't think this is tied to read-only mode. Probably displays incorrectly in read/write mode, too. I'll look into it.

**Comment by ricardoroth** [comment]
Thanks for your dedication to this project. I attach the two modes side to side... for the same annotation.

![image](https://user-images.githubusercontent.com/9203988/97744281-91ef2c80-1aac-11eb-857e-5596b786eb6a.png)

Checking at the html source code, it shows & lt ; instead of < 
Looks like this is being replaced somewhere within annotorius code...

**Comment by rsimon** [comment]
Been playing with this (and this is mostly a note to self, for later): Looks like this is not (economically...) viable to fix in the way this is currently implemented. Instead of using a `contentEditable` div for text entry, the widget should rather be built around a `textarea`. This will avoid HTML markup getting generated on newlines. For display in read-only mode, newlines can be retained with a `white-space:pre` CSS rule. 

I'll try to get the done soon-ish, for inclusion in the next release.

**Comment by rsimon** [comment]
This is now fixed in the latest [recogito-client-core](https://github.com/recogito/recogito-client-core) master branch + will go live with the next release.
