### ISSUE TITLE
Add delete annotation in editor

### ISSUE THREAD

**Issue by fcollonval** [annotorious/annotorious#77]
Hey progressing towards [v1](https://github.com/fcollonval/ipannotoryous/issues/1) of annotorious as Jupyter widget, I would like to add a button to easily delete an annotation.

What would you suggest as approach? I see either to propose a modification of the Editor to add a _Delete_ button in the footer (probably optionally) or to create a custom widget to add an header with a delete icon.

**Comment by rsimon** [comment]
Great - yes, having a general "Delete" button has been in my list for a long time (and having to delete every individual comment, tag, etc. of the annotation is pretty unintuitive). IMO this should be simply a modification to the Editor, in the footer as you say.

I think it will take a little bit of thought/precaution so that the button can be dis- and enabled through the API in a sensible way. (E.g. an app might not want to give some users delete privileges, or prevent deletion as soon as the annotation includes comments by other users, etc. Similar to the [__editable__ arg that was added to the comment widget a while back](https://github.com/recogito/annotorious/releases/tag/v2.1.0).) But that can be left for later.

Would you be willing to work on a pull request with a delete button in the Editor footer? I can take care of the auth-related plumbing later.

**Comment by fcollonval** [comment]
Thanks for the pointer

> Would you be willing to work on a pull request with a delete button in the Editor footer? I can take care of the auth-related plumbing later.

I should have time to do so - at least a first simple case without author-related feat.

**Comment by rsimon** [comment]
Wonderful - that would be great.

**Comment by rsimon** [comment]
Wonderful - that would be great.

**Comment by rsimon** [comment]
I finally got around to merging your pull request. Thanks again! I also added a mechanism that allows editor plugins to control whether the Remove button should be shown for a particular annotation or not. This will go live for all projects (RecogitoJS, Annotorious, AnnotoriousOSD) with the next updates.
